# Generated by Django 5.2.5 on 2025-09-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='total_amount',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
