# Generated by Django 5.2.5 on 2025-11-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paycash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='deal_user',
            field=models.CharField(blank=True, null=True, verbose_name='取引ユーザー'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='deal_type',
            field=models.CharField(choices=[('C', 'Charge'), ('P', 'Pay'), ('S', 'Send'), ('R', 'Recieve')], verbose_name='取引タイプ'),
        ),
    ]
