# Generated by Django 5.2.5 on 2025-11-12 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paycash', '0002_deal_deal_user_alter_deal_deal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='deal_check',
            field=models.BooleanField(blank=True, null=True, verbose_name='完了チェック'),
        ),
    ]
